apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: nitishkn/flask-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_DB
              value: "mydb"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret        # same secret used by MySQL
                  key: MYSQL_ROOT_PASSWORD  # base‑64 “admin”

